development:
  api_key: 657592
  api_secret: '3aa509e5677a191d8e9615c058a9464d9dc8503d'
  api_url: 'https://staging.opentok.com/hl'
  api_javascript_sdk: 'http://staging.tokbox.com/v0.91/js/TB.min.js'

production:
  api_key: 177891
  api_secret: 'fe79f53b71d2e7e4b89eafd06d1d45bd8adbb421'
  api_url: 'https://api.opentok.com/hl'
  api_javascript_sdk: 'http://static.opentok.com/v0.91/js/TB.min.js'
